version: '3'

vars:
  KUBECONFIG: ./kubeconfig.yaml
  TERRAFORM_DIR: terraform

tasks:
  # ========================
  # CLUSTER LIFECYCLE
  # ========================
  cluster:setup:
    desc: "Create new Kubernetes cluster on Linode"
    cmds:
      - scripts/setup-cluster.sh

  cluster:setup-complete:
    desc: "Complete setup: cluster + ArgoCD + applications"
    cmds:
      - task: cluster:setup
      - task: argocd:install
      - echo ""
      - echo "Complete setup finished!"
      - echo "================================"
      - echo "* Kubernetes cluster running with 2GB nodes"
      - echo "* ArgoCD installed with App of Apps pattern"
      - echo "* All applications deployed via port-forwarding"
      - echo ""
      - echo "📊 Available UIs (local access only):"
      - echo "* ArgoCD - task ui:argocd (https://localhost:8080)"
      - echo "* Prometheus - task ui:prometheus (http://localhost:9090)"
      - echo "* Grafana - task ui:grafana (http://localhost:3000)"
      - echo "* Loki - task ui:loki (http://localhost:3100)"
      - echo "* Hello World - task ui:hello (http://localhost:8081)"
      - echo "* Cost Dashboard - task ui:cost (http://localhost:8082)"
      - echo ""
      - echo "🔐 Authentication:"
      - echo "* ArgoCD password - task auth:argocd"
      - echo "* Grafana - admin/admin123"
      - echo ""
      - echo "📈 Other commands:"
      - echo "* Check status - task cluster:status"
      - echo "* Cost report - task reports:bill"

  cluster:teardown:
    desc: "Destroy cluster and clean up all Linode resources"
    cmds:
      - scripts/teardown-cluster.sh

  cluster:fresh:
    desc: "Reset to clean state: destroy cluster + clean files"
    cmds:
      - echo "Getting fresh state..."
      - echo "1. Destroying existing cluster (if any)..."
      - cd {{.TERRAFORM_DIR}} && tofu destroy -auto-approve || echo "No existing infrastructure to destroy"
      - echo "2. Cleaning up all local files..."
      - rm -f {{.KUBECONFIG}}
      - rm -f {{.TERRAFORM_DIR}}/terraform.tfstate*
      - rm -rf {{.TERRAFORM_DIR}}/.terraform/
      - echo "3. Reinitializing Terraform..."
      - cd {{.TERRAFORM_DIR}} && tofu init
      - echo ""
      - echo "Fresh state achieved!"
      - echo "Run 'task cluster:setup' to create a new cluster"

  cluster:status:
    desc: "Show cluster status and information"
    cmds:
      - cd {{.TERRAFORM_DIR}} && tofu output
      - echo ""
      - echo "Cluster Nodes:"
      - kubectl get nodes --kubeconfig={{.KUBECONFIG}}
      - echo ""
      - echo "System Pods:"
      - kubectl get pods -n kube-system --kubeconfig={{.KUBECONFIG}}

  # ========================
  # INFRASTRUCTURE MANAGEMENT
  # ========================
  infra:plan:
    desc: "Preview infrastructure changes (tofu plan)"
    cmds:
      - cd {{.TERRAFORM_DIR}} && tofu plan

  infra:apply:
    desc: "Apply infrastructure changes (tofu apply)"
    cmds:
      - cd {{.TERRAFORM_DIR}} && tofu apply

  infra:clean:
    desc: "Clean local terraform and kubernetes files"
    cmds:
      - rm -f {{.KUBECONFIG}}
      - rm -f {{.TERRAFORM_DIR}}/terraform.tfstate*
      - rm -rf {{.TERRAFORM_DIR}}/.terraform/
      - echo "Local files cleaned up"

  # ========================
  # KUBERNETES TOOLS
  # ========================
  k8s:kubectl:
    desc: "Run kubectl with cluster kubeconfig"
    cmds:
      - kubectl --kubeconfig={{.KUBECONFIG}} {{.CLI_ARGS}}

  k8s:logs:
    desc: "View pod logs"
    cmds:
      - kubectl logs {{.CLI_ARGS}} --kubeconfig={{.KUBECONFIG}}

  k8s:shell:
    desc: "Get shell in pod"
    cmds:
      - kubectl exec -it {{.CLI_ARGS}} --kubeconfig={{.KUBECONFIG}} -- /bin/bash

  k8s:k9s:
    desc: "Start K9s terminal UI"
    cmds:
      - |
        echo "K9s will be available in your terminal"
        echo "Starting K9s..."
        k9s --kubeconfig={{.KUBECONFIG}}

  # ========================
  # ARGOCD MANAGEMENT
  # ========================
  argocd:install:
    desc: "Install ArgoCD with App of Apps pattern"
    cmds:
      - scripts/install-argocd.sh

  auth:argocd:
    desc: "Get ArgoCD admin credentials"
    cmds:
      - |
        echo "ArgoCD Login Credentials:"
        echo "=========================="
        echo "URL: https://localhost:8080 (use task ui:argocd)"
        echo "Username: admin"
        echo -n "Password: "
        kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" --kubeconfig={{.KUBECONFIG}} | base64 -d
        echo ""

  # ========================
  # UI ACCESS (PORT FORWARDING)
  # ========================
  ui:argocd:
    desc: "Port forward to ArgoCD UI (https://localhost:8080)"
    cmds:
      - |
        echo "ArgoCD UI will be available at https://localhost:8080"
        echo "Username: admin (get password with: task auth:argocd)"
        echo "Starting port forwarding..."
        kubectl port-forward svc/argocd-server -n argocd 8080:443 --kubeconfig={{.KUBECONFIG}}

  ui:prometheus:
    desc: "Port forward to Prometheus (http://localhost:9090)"
    cmds:
      - |
        echo "Prometheus UI will be available at http://localhost:9090"
        echo "Starting port forwarding..."
        kubectl port-forward svc/prometheus -n monitoring 9090:9090 --kubeconfig={{.KUBECONFIG}}

  ui:grafana:
    desc: "Port forward to Grafana (http://localhost:3000)"
    cmds:
      - |
        echo "Grafana UI will be available at http://localhost:3000"
        echo "Username: admin"
        echo "Password: admin123"
        echo "Dashboards: Kubernetes Cluster Overview, Kubernetes Logs Overview"
        echo "Starting port forwarding..."
        kubectl port-forward svc/grafana -n monitoring 3000:3000 --kubeconfig={{.KUBECONFIG}}

  ui:loki:
    desc: "Port forward to Loki (http://localhost:3100)"
    cmds:
      - |
        echo "Loki API will be available at http://localhost:3100"
        echo "Use with LogQL queries or connect from Grafana"
        echo "Starting port forwarding..."
        kubectl port-forward svc/loki -n logging 3100:3100 --kubeconfig={{.KUBECONFIG}}

  ui:hello:
    desc: "Port forward to Hello World demo (http://localhost:8081)"
    cmds:
      - |
        echo "Hello World demo app will be available at http://localhost:8081"
        echo "Starting port forwarding..."
        kubectl port-forward svc/hello-world -n demo 8081:80 --kubeconfig={{.KUBECONFIG}}

  ui:cost:
    desc: "Port forward to Cost Dashboard (http://localhost:8082)"
    cmds:
      - |
        echo "Cost Dashboard will be available at http://localhost:8082"
        echo "Starting port forwarding..."
        kubectl port-forward svc/cost-dashboard -n cost-monitoring 8082:80 --kubeconfig={{.KUBECONFIG}}

  # ========================
  # REPORTS & UTILITIES
  # ========================
  reports:bill:
    desc: "Generate Linode billing report (bill.pdf)"
    cmds:
      - uv run scripts/generate_billing_report.py

  # ========================
  # LEGACY COMPATIBILITY
  # ========================
  setup:
    desc: "Legacy alias for cluster:setup"
    cmds:
      - task: cluster:setup

  setup-complete:
    desc: "Legacy alias for cluster:setup-complete"
    cmds:
      - task: cluster:setup-complete

  teardown:
    desc: "Legacy alias for cluster:teardown"
    cmds:
      - task: cluster:teardown

  fresh:
    desc: "Legacy alias for cluster:fresh"
    cmds:
      - task: cluster:fresh

  status:
    desc: "Legacy alias for cluster:status"
    cmds:
      - task: cluster:status

  plan:
    desc: "Legacy alias for infra:plan"
    cmds:
      - task: infra:plan

  apply:
    desc: "Legacy alias for infra:apply"
    cmds:
      - task: infra:apply

  clean:
    desc: "Legacy alias for infra:clean"
    cmds:
      - task: infra:clean

  kubectl:
    desc: "Legacy alias for k8s:kubectl"
    cmds:
      - task: k8s:kubectl

  logs:
    desc: "Legacy alias for k8s:logs"
    cmds:
      - task: k8s:logs

  shell:
    desc: "Legacy alias for k8s:shell"
    cmds:
      - task: k8s:shell

  k9s:
    desc: "Legacy alias for k8s:k9s"
    cmds:
      - task: k8s:k9s

  install-argocd:
    desc: "Legacy alias for argocd:install"
    cmds:
      - task: argocd:install

  argocd-password:
    desc: "Legacy alias for auth:argocd"
    cmds:
      - task: auth:argocd

  argocd-ui:
    desc: "Legacy alias for ui:argocd"
    cmds:
      - task: ui:argocd

  monitoring-ui:
    desc: "Legacy alias for ui:prometheus"
    cmds:
      - task: ui:prometheus

  grafana-ui:
    desc: "Legacy alias for ui:grafana"
    cmds:
      - task: ui:grafana

  loki-ui:
    desc: "Legacy alias for ui:loki"
    cmds:
      - task: ui:loki

  demo-app:
    desc: "Legacy alias for ui:hello"
    cmds:
      - task: ui:hello

  cost-dashboard:
    desc: "Legacy alias for ui:cost"
    cmds:
      - task: ui:cost

  bill:
    desc: "Legacy alias for reports:bill"
    cmds:
      - task: reports:bill